### ISSUE TITLE
add instances for vector types?

### ISSUE THREAD

**Issue by chessai** [andrewthad/contiguous#22]
it might be useful to provide instances for vector. there is a similar (but slightly better) story to primitive with the vector api being annoying to use in the presence of needing more than one vector type. most people elect to just import things from vector qualified rather than use the generic interface, which isn't very clean compared to Contiguous.

**Comment by andrewthad** [comment]
Because we have `lift` and `unlift` (for conversion to/from `ArrayArray#`), it is not possible to write these instances.

**Comment by chessai** [comment]
Dang. That sucks. What are lift/unlift used for anyway? Why did you need them?

**Comment by andrewthad** [comment]
They give us the ability to store any `Contiguous` type inside of an `UnliftedArray`. More importantly, they let us unpack polymorphic `Contiguous` types into data constructors. I take advantage of this in [primitive-containers](https://github.com/andrewthad/primitive-containers/blob/3b7c43a0fc56367f0c717c14d19971c8876c806a/src/Data/Map/Interval/DBTS/Internal.hs#L62-L89) to avoid unneeded boxing in interval maps. The resulting code is ugly, but it is also optimal.

**Comment by chessai** [comment]
dang.

**Comment by chessai** [comment]
I thought of this when you first wrote your comment, but was reluctant to write it:

Is it possible to move those out to a subclass of Contiguous? That way, vector types get instances of Contiguous as well.

**Comment by andrewthad** [comment]
That is possible, and it would make it possible to handle boxed vectors.  I don’t think unboxed vectors would work though.  The vector library puts constraints on the instances while this library uses ContraintKinds.

 In my mind though, the bigger problem is that  sliced vectors and unsliced vectors have totally different  performance characteristics for certain operations.  These performance differences mean that users cannot write algorithms the same way. For sliced vectors, uncons  is a perfectly legitimate (and safe) way to  pattern match.  When inlined, it should generate optimal code.  But, this same operation is nearly useless for unsliced vectors  since it makes a copy.

 Here’s another example where the differences dig beyond just performance and into the semantics:  taking the tail of a mutable array. In the vector library, the results aliases the argument array, but with unsliced vectors,  this must allocate a brand new array.  The only internally consistent thing to do would be to always allocate the brand new array, but  this makes the interface inconsistent with the API that vector exposes.

 Perhaps a better way to accomplish the goal of improving  inter-operability with a vector would be to add things like:

    withVector :: Vector a -> (Array a -> Int -> Int -> b) -> b

 I’m not sure to what extent it is possible to introduce air type class and type family Sliceable/Slice  to generalize this.  Regardless of whether it was a sub class of Contiguous  or whether the  additional function  and type family lived inside of Contiguous,  I suspect that you may still run into problems with unboxed arrays.  Well, that and the fact that Data.Vector  does not export the data constructor.

**Comment by chessai** [comment]
too much trouble. if someone really wants this, then maybe we could work it out.
