### ISSUE TITLE
0.4 release?

### ISSUE THREAD

**Issue by chessai** [andrewthad/contiguous#23]
what do we need for an 0.4 release?

**Comment by andrewthad** [comment]
I just looked over the haddocks that get generated, and the only documentation-related problem I see is that their is a "Monadic Mapping" section with nothing in it. It should be removed since the "Traversals" section has these functions. I'll try building and testing `automata` and `primitive-containers` against master to make sure there weren't any behavioral regressions that affect them.

**Comment by andrewthad** [comment]
`resize` is not exported.

**Comment by chessai** [comment]
both issues fixed

**Comment by andrewthad** [comment]
Both `automata` and `primitive-containers` now build against the new contiguous. Additionally, their test suites pass.

**Comment by chessai** [comment]
Nice. Can i make a new release this afternoon?

**Comment by chessai** [comment]
Might want to test the unfoldr family of functions against vector's

**Comment by andrewthad** [comment]
Yeah, do a release whenever you feel comfortable with it.

**Comment by chessai** [comment]
okay

**Comment by chessai** [comment]
this is done: http://hackage.haskell.org/package/contiguous-0.4/docs/Data-Primitive-Contiguous.html
