### ISSUE TITLE
Separate out lift and unlift into a superclass?

### ISSUE THREAD

**Issue by Boarders** [andrewthad/contiguous#38]
I am trying to write a primitive-array backed variant of unboxed vectors using SOA style layout. I would like to use this typeclass but I don't think it is possible to write `lift` and `unlift`. I wanted to ask:

1. Am I incorrect in this assumption?

2. If not, how would you feel about a version which splits the typeclass up into those things that can be lifted and unlifted and the other operations (I note that almost all the functions barring fast semi-equality checks do not use these methods)?

edit: Actually I think this kind of thing just fundamentally doesn't work with contiguous but I'd be interested to hear if you think otherwise.

**Comment by Boarders** [comment]
I thought about this some more and realized it is only sensible if we have a typeclass which takes the type as argument like vector does:
```haskell
type Contiguous :: (Type -> Type) ->  Type -> Constraint
class Contiguous (arr :: Type -> Type) (a :: Type) where
  type family Mutable arr = (r :: Type -> Type -> Type) | r -> arr
  type family Element arr :: Type -> Constraint
  new :: (PrimMonad m, Element arr a) => Int -> m (Mutable arr (PrimState m) a)
   --
```

Sorry for polluting your issues!

**Comment by andrewthad** [comment]
I'm not inclined to try to change this in `contiguous`, but I think your observations are accurate. One thing about SoA that is important but not accounted for by `vector`'s treatment of SoA data structures (and wouldn't be accounted for by contiguous either) is that it's important to be able to pull the arrays apart and work on them individually. Having arrays be indexed by length helps a ton with doing this safely. For example:

    data MySoa n = MySoa
      { ages :: Vec n Int64
      , names :: Vec n ShortText
      }
    map :: (a -> b) -> Vec n a -> Vec n b
    passSomeTime :: MySoa n -> MySoa n
    passSomeTime MySoa{ages=ages0, names=names0} =
      MySoa{ages=map (+1) ages0,names=names0}

This works because `map` (and lots of other traversal functions) preserves the length of the array. It's useful to have the typechecker help us with this. Unfortunately, you quickly get into the territory of existential quantification when you try to keep building something like this out. I think that any approach to SoA needs to explicitly track length though because otherwise, the question of "are these arrays the same length" has to be tracked in the programmer's head, which I find unpleasant.

Closing because I'm not planning on changing this, but I'm happy to continue discussion on this thread if you have other thoughts.

**Comment by Boarders** [comment]
Thanks for the insights! I am working on a library to do this so may put up some more observations that are relevant.
